# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $DEPLOY_HOOK_URL
    env:
      DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
